### ISSUE TITLE
Switch is missing prioqueue.h

### ISSUE THREAD

**Issue by rmh1480** [phaistos-networks/TANK#57]
Hi Mark,

I am trying to compile Trinity using Switch from this project and it is missing prioqueue.h

./docset_iterators.h:6:10: fatal error: 'prioqueue.h' file not found

Can you please add the file?
Best,
Raja

**Comment by markpapadakis** [comment]
@rmh1480 I am very sorry for that snafu. Pushed an update that includes that file. Thank you very much for reporting it.
