### ISSUE TITLE
Problem with Client when receiving more than one consume message

### ISSUE THREAD

**Issue by krconv** [phaistos-networks/TANK#66]
When the client receives multiple consume messages during a single `poll()` period, there seems to be a problem where some of the messages' contents returned by `consumed()` are corrupted/bad pointers. This can cause errors due to the corrupted `char* data()` pointer or `size_t size()` for `consumed_msg`, such as a `SEGFAULT`.

I've created this branch to reproduce the issue: https://github.com/krconv/TANK/tree/client-tests
```sh
git clone https://github.com/krconv/TANK/tree/client-tests
cd TANK
git checkout client-tests
docker build . -t tank-test
while [ $? -eq 0 ] ; do docker run -it tank-test ; done
```

My output:
```
Note: Google Test filter = ClientTest.CanConsumeSimultaneously
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ClientTest
[ RUN      ] ClientTest.CanConsumeSimultaneously
static void client::test::ClientTest::createEmptyTankTopics()
static void client::test::ClientTest::startTank()
<=TANK=> v0.77 | 2 topics registered, 2 partitions; will listen for new connections at 127.0.0.1:11011
(C) Phaistos Networks, S.A. - http://phaistosnetworks.gr/. Licensed under the Apache License

tests/client-test.cpp:184: Failure
      Expected: 1
To be equal to: pMessage->seqNum
      Which is: 140039336233528
[segfault]
```

**Comment by markpapadakis** [comment]
Thank you for the report. There is a new TANK server and client release currently under testing which fixes this and other problems reported by other users. It will be a few more days before it’s ready for a public release but it’s worrh it believe. Many new features and performance improvements.

**Comment by markpapadakis** [comment]
@krconv you can certainly explicitly disable that optimisation and it should work fine until the new release is pushed upstream

**Comment by krconv** [comment]
Thanks for the help!
