### ISSUE TITLE
Crashes when system time is before Jan 05 2016 08:27:06

### ISSUE THREAD

**Issue by krconv** [phaistos-networks/TANK#67]
We've noticed that TANK will abort when the system time is before 2016. What is the purpose of this check? The system that we are using TANK on doesn't always have access to a centralized clock, so it is possible for it to start at a date far in the past before the time gets corrected.

This seems to be the check that causes the `abort`, in `Switch/timings.h:175`
```c++
else if (unlikely(tv.tv_sec < 1451982426u))
{
    abort();
}
```

**Comment by markpapadakis** [comment]
Oh, that's odd. I think this was left there for sanity check reasons. Please feel free to remove it from there and recompile.
